doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        #driver_class: Realestate\MssqlBundle\Driver\PDODblib\Driver
        driver: 'pdo_mysql'
        host: 127.0.0.1
       
        dbname: dbprocede
        user: root
       
  
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
